// Generated by https://quicktype.io

class Trending {
  int page;
  int totalResults;
  int totalPages;
  List<Result> results;

  Trending({
    this.page,
    this.totalResults,
    this.totalPages,
    this.results,
  });
}

class Result {
  double popularity;
  int voteCount;
  bool video;
  String posterPath;
  int id;
  String backdropPath;
  String title;
  double voteAverage;
  String overview;
  String releaseDate;

  Result({
    this.popularity,
    this.voteCount,
    this.video,
    this.posterPath,
    this.id,
    this.backdropPath,
    this.title,
    this.voteAverage,
    this.overview,
    this.releaseDate,
  });

  factory Result.fromJSON(Map<String, dynamic> movie) {
    return Result(
        popularity: movie["popularity"],
        voteCount: movie["vote_count"],
        video: movie["video"],
        posterPath: movie["poster_path"],
        id: movie["id"],
        backdropPath: movie["backdrop_path"],
        title: movie["title"],
        voteAverage: movie["vote_average"] is int
            ? (movie["vote_average"] as int).toDouble()
            : movie["vote_average"],
        overview: movie["overview"],
        releaseDate: movie["release_date"]);
  }
}
